### ISSUE TITLE
[Setup do AWS S3] Criar bucket plataforma-dados-processing-<id_conta_aws>

### ISSUE THREAD

**Issue by renata-olivmachado** [SouJunior/dashboard-midias#14]
TASK da story [#13](https://github.com/SouJunior/dashboard-midias/issues/13)

**Criar bucket plataforma-dados-processing-<id_conta_aws>**

**Comment by renata-olivmachado** [comment]
@hdind Pedro, não tinhamos nomeado o responsável dessa tarefa, vou colocar a @Bruna-Krobel que vai criar a conta do AWS

**Comment by Bruna-Krobel** [comment]
Segue a imagem do bucket criado.

![Image](https://github.com/SouJunior/dashboard-midias/assets/129909002/07d1ef9d-7a1c-4829-85a2-f7f85175d6f4)
