### ISSUE TITLE
[Setup do AWS S3]  Criar bucket plataforma-dados-raw-<id_conta_aws>

### ISSUE THREAD

**Issue by renata-olivmachado** [SouJunior/dashboard-midias#15]
Tarefa da Story [#13](https://github.com/SouJunior/dashboard-midias/issues/13)

**Criar bucket plataforma-dados-raw-<id_conta_aws>**

**Comment by Bruna-Krobel** [comment]
@renata-olivmachado estou com uma dúvida, essa task é duplicada em relação a https://github.com/SouJunior/dashboard-midias/issues/14 ?

**Comment by renata-olivmachado** [comment]
Está mesmo Bruna, erro meu! 
@hdind na hora de refazer os cards acabei fazendo copiando a tarefa errada e criei as duas Task Iguais. Você consegue corrigi-lá com a outra tarefa que você tinha escrito dentro de Setup do AWS S3. Como eu apaguei não sei o que seria a outra tarefa.

**Comment by hdind** [comment]
Eu ajustei o nome da tarefa, @Bruna-Krobel, é para criar 2 buckets, essa tarefa é a criação do bucket "plataforma-dados-raw-<id_conta_aws>"

**Comment by Bruna-Krobel** [comment]
Bucket criado!

![Image](https://github.com/SouJunior/dashboard-midias/assets/129909002/30ad352f-c4e6-4959-b0bb-408a43a90268)
