### ISSUE TITLE
[Atualização manual do dash LinkedIn] Testar mesclar 2 meses como exemplo

### ISSUE THREAD

**Issue by renata-olivmachado** [SouJunior/dashboard-midias#29]

**Comment by Moscarde** [comment]
Em `Drive/CLEAN/Concatenated ` estão dispostos arquivos .csv referente a junção de extrações tratadas de dois meses.



![Image](https://github.com/SouJunior/dashboard-midias/assets/78855746/82249f1d-b4e7-4179-b0e0-f8cb3ac92046)

**Comment by Moscarde** [comment]
Arquivos mesclados e doc disponíveis em `DRIVE/CLEAN`
Abaixo contém o conteúdo da doc

# Arquivo: Concorrentes

## Tabela: Concorrentes

### Colunas Originais

- Page
- Total de seguidores
- Novos seguidores
- Total de engajamentos da publicação
- Total de publicações

### Colunas Finais

- **Data referência**
- Page
- Total de seguidores
- Novos seguidores
- Total de engajamentos da publicação
- Total de publicações

### Resumo de mudanças

- Removido primeiro registro
- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

Coluna \[Total de seguidores\] possui valores estáticos entre extrações de 15 dias. (Não respeitam o recorte da extração)

# Arquivo: Conteúdo

## Tabela: Métricas

### Colunas Originais

- Data
- Impressões (orgânicas)
- Impressões (patrocinadas)
- Impressões (total)
- Impressões únicas (orgânicas)
- Cliques (orgânicos)
- Cliques (patrocinados)
- Cliques (total)
- Reações (orgânicas)
- Reações (patrocinadas)
- Reações (total)
- Comentários (orgânicos)
- Comentários (patrocinados)
- Comentários (total)
- Compartilhamentos (orgânicos)
- Compartilhamentos (patrocinados)
- Compartilhamentos (total)
- Taxa de engajamento (orgânico)
- Taxa de engajamento (patrocinado)
- Taxa de engajamento (total)

### Colunas Finais

\*Sem alterações

### Resumo de mudanças

- Removido primeiro registro
- Adicionado conteúdo de uma extração mais recente

### Observações

Colunas \[Cliques, Reações, Comentários, Compartilhamentos\] possuem valores negativos por motivos desconhecidos, influenciando o cálculo da coluna \[Taxa de engajamento\]

## Tabela: Todas as publicações

### Colunas Originais

- Título da publicação
- Link da publicação
- Tipo de publicação
- Nome da campanha
- Publicada por
- Criação
- Data de início da campanha
- Data de término da campanha
- Público
- Impressões
- Visualizações (excluindo visualizações de vídeo fora do site)
- Visualizações fora do site
- Cliques
- Taxa de cliques (CTR)
- Gostaram
- Comentários
- Compartilhamentos
- Seguidores
- Taxa de engajamento
- Tipo de conteúdo

### Colunas Finais

\*Sem alterações

### Resumo de mudanças

- Removido primeiro registro
- Adicionado conteúdo de uma extração mais recente

### Observações

Analisar se as métricas da postagem são gerais ou um recorte temporal até o período da extração.

Exemplo:

Criação da postagem: 10 de janeiro

Período de extração 1-15 de janeiro

Data realizada a extração: 1 de junho

**As métricas registradas na tabela são referentes ao recorte ou ao período total até a data da extração? Em extrações recentes pode ser necessário excluir postagens muito novas.**

# Arquivo: Seguidores

## Tabela: Novos Seguidores

### Colunas Originais

- Data
- Seguidores patrocinados
- Seguidores orgânicos
- Total de seguidores

### Colunas Finais

\*Sem alterações

### Resumo de mudanças

- Adicionado conteúdo de uma extração mais recente

### Observações

…

## Tabela: Localidade

### Colunas Originais

- Localidade
- Total de seguidores

### Colunas Finais

- **Data referência**
- Localidade
- Total de seguidores

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

Os valores do total de seguidores não respeitam o recorte do período de extração.

## Tabela: Função

### Colunas Originais

- Função
- Total de seguidores

### Colunas Finais

- **Data referência**
- Função
- Total de seguidores

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

Os valores do total de seguidores não respeitam o recorte do período de extração.

## Tabela: Nível de experiência

### Colunas Originais

- Nível de experiência
- Total de seguidores

### Colunas Finais

- **Data referência**
- Nível de experiência
- Total de seguidores

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

Os valores do total de seguidores não respeitam o recorte do período de extração.

## Tabela: Setor

### Colunas Originais

- Setor
- Total de seguidores

### Colunas Finais

- **Data referência**
- Setor
- Total de seguidores

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

Os valores do total de seguidores não respeitam o recorte do período de extração.

## Tabela: Tamanho da empresa

### Colunas Originais

- Tamanho da empresa
- Total de seguidores

### Colunas Finais

- **Data referência**
- Tamanho da empresa
- Total de seguidores

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

Os valores do total de seguidores não respeitam o recorte do período de extração.

# Arquivo: Visitantes

## Tabela: Métricas de visitantes

### Colunas Originais

- Data
- Visualizações da página
- Visão geral (computadores)
- Visualizações da página Visão geral (dispositivos móveis)
- Visualizações da página Visão geral (total)
- Visitantes únicos da página Visão geral (computadores)
- Visitantes únicos da página Visão geral (dispositivos móveis)
- Visitantes únicos da página Visão geral (total)
- Visualizações da página Dia a dia (computadores)
- Visualizações da página Dia a dia (dispositivos móveis)
- Visualizações da página Dia a dia (total)
- Visitantes únicos da página Dia a dia (computadores)
- Visitantes únicos da página Dia a dia (dispositivos móveis)
- Visitantes únicos da página Dia a dia (total)
- Visualizações da página Vagas (computadores)
- Visualizações da página Vagas (dispositivos móveis)
- Visualizações da página Vagas (total)
- Visitantes únicos da página Vagas (computadores)
- Visitantes únicos da página Vagas (dispositivos móveis)
- Visitantes únicos da página Vagas (total)
- Total de visualizações da página (computadores)
- Total de visualizações da página (dispositivos móveis)
- Total de visualizações da página (total)
- Total de visitantes únicos (computadores)
- Total de visitantes únicos (dispositivos móveis)
- Total de visitantes únicos (total)

### Colunas Finais

\*Sem alterações

### Resumo de mudanças

- Adicionado conteúdo de uma extração mais recente

### Observações

…

## Tabela: Localidade

### Colunas Originais

- Localidade
- Total de visualizações

### Colunas Finais

- **Data referência**
- Localidade
- Total de visualizações

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

…

## Tabela: Função

### Colunas Originais

- Função
- Total de visualizações

### Colunas Finais

- **Data referência**
- Função
- Total de visualizações

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

…

## Tabela: Nível de experiência

### Colunas Originais

- Nível de experiência
- Total de visualizações

### Colunas Finais

- **Data referência**
- Nível de experiência
- Total de visualizações

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

…

## Tabela: Setor

### Colunas Originais

- Setor
- Total de visualizações

### Colunas Finais

- **Data referência**
- Setor
- Total de visualizações

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

…

## Tabela: Tamanho da empresa

### Colunas Originais

- Tamanho da empresa
- Total de visualizações

### Colunas Finais

- **Data referência**
- Tamanho da empresa
- Total de visualizações

### Resumo de mudanças

- Adicionado coluna Data referência
  - Valores dessa coluna são no formato data e o valor é referente ao último dia do período de extração
- Adicionado conteúdo de uma extração mais recente

### Observações

…

**Comment by Amandlsp** [comment]
@gabrielpiment @Moscarde @hdind Tabelas validadas! Só recomendo uma formatação padrão pra data AAAA-MM-DD. Não sei se já fizemos alguma transformação nesses dados antes ou se será feito após a liberação do Banco de Dados!
