### ISSUE TITLE
[Atualização manual do dash LinkedIn] Baixar todas as versões em blocos de 15 dias de um ano para trás até agora.

### ISSUE THREAD

**Issue by renata-olivmachado** [SouJunior/dashboard-midias#30]

**Comment by Moscarde** [comment]
Arquivos das extrações estão disponíveis em RAW/CATEGORIA/ANO/MÊS.
Extrações para essa tarefa estão sendo executadas de forma manual e diária, afim de minimizar riscos de bloqueios pelo servidor.

### Log das extrações:
Extração diária realizada em: 22/05/24
Extração período 01/06/23 -> 15/06/23 
Extração período 16/06/23 -> 30/06/23 

Extração diária realizada em: 23/05/24
Extração período 01/07/23 -> 15/07/23 
Extração período 16/07/23 -> 31/07/23 

Extração diária realizada em: 25/05/24
Extração período 01/08/23 -> 15/08/23 
Extração período 16/08/23 -> 31/08/23 

Extração diária realizada em: 27/05/24
Extração período 01/09/23 -> 15/09/23 
Extração período 16/09/23 -> 30/09/23

Extração diária realizada em: 28/05/24
Extração período 01/10/23 -> 15/10/23
Extração período 16/10/23 -> 30/10/23

Extração diária realizada em: 30/05/24
Extração período 01/11/23 -> 15/11/23
Extração período 16/11/23 -> 30/11/23

Extração diária realizada em: 02/06/24
Extração período 01/12/23 -> 15/12/23
Extração período 16/12/23 -> 31/12/23

Extração diária realizada em: 03/06/24
Extração período 01/01/24 -> 15/01/24
Extração período 16/01/24 -> 31/01/24

Extração diária realizada em: 04/06/24
Extração período 01/02/24 -> 15/02/24
Extração período 16/02/24 -> 29/02/24

Extração diária realizada em: 05/06/24
Extração período 01/03/24 -> 15/03/24
Extração período 16/03/24 -> 31/03/24

Extração diária realizada em: 05/06/24
Extração período 01/04/24 -> 15/04/24
Extração período 16/04/24 -> 30/04/24

Extração diária realizada em: 08/06/24
Extração período 01/05/24 -> 15/05/24
Extração período 16/05/24 -> 31/05/24
