### ISSUE TITLE
[Atualização manual do dash LinkedIn] Fazer o processo documentando a extração

### ISSUE THREAD

**Issue by renata-olivmachado** [SouJunior/dashboard-midias#31]

**Comment by Moscarde** [comment]
# Passo a Passo para Extração de Dados Estatísticos do LinkedIn

Este documento detalha os passos necessários para extrair dados estatísticos de uma página do LinkedIn nas categorias de conteúdo, seguidores, visitantes e concorrentes, filtrados pelo período de 15 dias.

## Requisitos

- Acesso à conta do LinkedIn com permissões de administrador na página desejada.
    

## Links Diretos

- [Concorrentes](https://www.linkedin.com/company/82326952/admin/analytics/competitors/)
    
- [Conteúdo](https://www.linkedin.com/company/82326952/admin/analytics/updates/)
    
- [Seguidores](https://www.linkedin.com/company/82326952/admin/analytics/followers/)
    
- [Visitantes](https://www.linkedin.com/company/82326952/admin/analytics/visitors/)
    

## Passo a Passo

### 1. Acessar o LinkedIn

1. Abra seu navegador e acesse o [LinkedIn](https://www.linkedin.com).
    
2. Faça login com suas credenciais.
    

### 2. Navegar até cada página de extração

#### a. Concorrentes

#### b. Conteúdo

#### c. Seguidores

#### d. Visitantes

1. Clicar no campo de data
    
2. Clicar no campo “Personalizado”
    
3. Filtrar pelo período de 15 dias (01-15, 15-Final do mês)
    
4. Clicar no botão exportar
